sonar.sources=contracts,scripts
sonar.tests=test,test-js
sonar.exclusions=node_modules/**,artifacts/**,cache/**
sonar.coverage.exclusions=contracts/**
sonar.javascript.lcov.reportPaths=coverage-js/lcov.info

